import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutterotp_firebase/app/Constant/sizeConstant.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';

import '../../../../main.dart';
import '../Home/controller/Homecontroller.dart';

class AddUpvasController extends GetxController {
  RxString selectedDate = "".obs;
  RxBool isSavarSelected = true.obs;
  RxBool isSanjSelected = false.obs;
  RxBool isFullDaySelected = false.obs;
  RxBool hasData = false.obs;
  RxList<Selected> getDataList = RxList<Selected>([]);
  RxList<String> list = RxList<String>([]);
  RxString dropdownValue = "1".obs;
  RxString selectedDataDate = "".obs;

  @override
  void onInit() {
    selectedDate.value =
        DateFormat('dd MMM, yyyy').format(DateTime.now()).toString();
    selectedDataDate.value =
        DateFormat('dd/MM/yyyy').format(DateTime.now()).toString();
    data();
    super.onInit();
  }

  data({String text = "savar"}) async {
    hasData.value = false;
    list.clear();
    await Future.delayed(const Duration(milliseconds: 50));

    if (getSelectedText() == "Full") {
      RxList<Selected> getDataListSavar = RxList<Selected>([]);
      RxList<Selected> getDataListSanj = RxList<Selected>([]);
      if (!isNullEmptyOrFalse(box.read(selectedDataDate.value + "Savar"))) {
        getDataListSavar.value = ((jsonDecode(box.read(selectedDataDate.value + "Savar"))
                        as List<dynamic>)
                    .toList())
                .map((e) => Selected.fromJson(e))
                .toList();
      } else {
        box.write(
            selectedDataDate.value + "Savar",
            jsonEncode(RxList<Selected>([
              Selected(isSelected: false.obs, name: "1".obs),
              Selected(isSelected: false.obs, name: "2".obs),
              Selected(isSelected: false.obs, name: "3".obs),
              Selected(isSelected: false.obs, name: "4".obs),
              Selected(isSelected: false.obs, name: "5".obs),
              Selected(isSelected: false.obs, name: "6".obs),
              Selected(isSelected: false.obs, name: "7".obs),
              Selected(isSelected: false.obs, name: "8".obs),
              Selected(isSelected: false.obs, name: "9".obs),
              Selected(isSelected: false.obs, name: "10".obs),
              Selected(isSelected: false.obs, name: "11".obs),
              Selected(isSelected: false.obs, name: "12".obs),
              Selected(isSelected: false.obs, name: "13".obs),
              Selected(isSelected: false.obs, name: "14".obs),
              Selected(isSelected: false.obs, name: "15".obs),
              Selected(isSelected: false.obs, name: "16".obs),
              Selected(isSelected: false.obs, name: "17".obs),
              Selected(isSelected: false.obs, name: "18".obs),
              Selected(isSelected: false.obs, name: "19".obs),
              Selected(isSelected: false.obs, name: "20".obs),
              Selected(isSelected: false.obs, name: "21".obs),
              Selected(isSelected: false.obs, name: "22".obs),
              Selected(isSelected: false.obs, name: "23".obs),
              Selected(isSelected: false.obs, name: "24".obs),
              Selected(isSelected: false.obs, name: "25".obs),
              Selected(isSelected: false.obs, name: "26".obs),
              Selected(isSelected: false.obs, name: "27".obs),
              Selected(isSelected: false.obs, name: "28".obs),
              Selected(isSelected: false.obs, name: "29".obs),
              Selected(isSelected: false.obs, name: "30".obs),
              Selected(isSelected: false.obs, name: "31".obs),
              Selected(isSelected: false.obs, name: "32".obs),
              Selected(isSelected: false.obs, name: "33".obs),
              Selected(isSelected: false.obs, name: "34".obs),
              Selected(isSelected: false.obs, name: "35".obs),
              Selected(isSelected: false.obs, name: "36".obs),
              Selected(isSelected: false.obs, name: "37".obs),
              Selected(isSelected: false.obs, name: "38".obs),
              Selected(isSelected: false.obs, name: "39".obs),
              Selected(isSelected: false.obs, name: "40".obs),
              Selected(isSelected: false.obs, name: "41".obs),
              Selected(isSelected: false.obs, name: "42".obs),
              Selected(isSelected: false.obs, name: "43".obs),
              Selected(isSelected: false.obs, name: "44".obs),
              Selected(isSelected: false.obs, name: "45".obs),
              Selected(isSelected: false.obs, name: "46".obs),
              Selected(isSelected: false.obs, name: "47".obs),
              Selected(isSelected: false.obs, name: "48".obs),
              Selected(isSelected: false.obs, name: "49".obs),
              Selected(isSelected: false.obs, name: "50".obs),
              Selected(isSelected: false.obs, name: "51".obs),
              Selected(isSelected: false.obs, name: "52".obs),
              Selected(isSelected: false.obs, name: "53".obs),
              Selected(isSelected: false.obs, name: "54".obs),
              Selected(isSelected: false.obs, name: "55".obs),
              Selected(isSelected: false.obs, name: "56".obs),
              Selected(isSelected: false.obs, name: "57".obs),
              Selected(isSelected: false.obs, name: "58".obs),
              Selected(isSelected: false.obs, name: "59".obs),
              Selected(isSelected: false.obs, name: "61".obs),
              Selected(isSelected: false.obs, name: "62".obs),
              Selected(isSelected: false.obs, name: "63".obs),
              Selected(isSelected: false.obs, name: "64".obs),
              Selected(isSelected: false.obs, name: "65".obs),
              Selected(isSelected: false.obs, name: "P1".obs),
              Selected(isSelected: false.obs, name: "P2".obs),
              Selected(isSelected: false.obs, name: "P3".obs),
              Selected(isSelected: false.obs, name: "P4".obs),
              Selected(isSelected: false.obs, name: "P5".obs),
              Selected(isSelected: false.obs, name: "P6".obs),
              Selected(isSelected: false.obs, name: "P7".obs),
              Selected(isSelected: false.obs, name: "P8".obs),
              Selected(isSelected: false.obs, name: "P9".obs),
              Selected(isSelected: false.obs, name: "P10".obs),
              Selected(isSelected: false.obs, name: "S1".obs),
              Selected(isSelected: false.obs, name: "S2".obs),
              Selected(isSelected: false.obs, name: "S3".obs),
              Selected(isSelected: false.obs, name: "S4".obs),
              Selected(isSelected: false.obs, name: "S5".obs),
              Selected(isSelected: false.obs, name: "S6".obs),
              Selected(isSelected: false.obs, name: "S7".obs),
              Selected(isSelected: false.obs, name: "S8".obs),
              Selected(isSelected: false.obs, name: "S9".obs),
              Selected(isSelected: false.obs, name: "S10".obs),
              Selected(isSelected: false.obs, name: "S11".obs),
              Selected(isSelected: false.obs, name: "S12".obs),
              Selected(isSelected: false.obs, name: "S13".obs),
              Selected(isSelected: false.obs, name: "S14".obs),
              Selected(isSelected: false.obs, name: "S15".obs),
              Selected(isSelected: false.obs, name: "S16".obs),
              Selected(isSelected: false.obs, name: "S17".obs),
              Selected(isSelected: false.obs, name: "M18".obs),
              Selected(isSelected: false.obs, name: "M19".obs),
              Selected(isSelected: false.obs, name: "M20".obs),
              Selected(isSelected: false.obs, name: "M21".obs),
              Selected(isSelected: false.obs, name: "M22".obs),
              Selected(isSelected: false.obs, name: "SE1".obs),
              Selected(isSelected: false.obs, name: "SE2".obs),
              Selected(isSelected: false.obs, name: "SE3".obs),
              Selected(isSelected: false.obs, name: "SE4".obs),
              Selected(isSelected: false.obs, name: "SE5".obs),
              Selected(isSelected: false.obs, name: "SE6".obs),
              Selected(isSelected: false.obs, name: "SE7".obs),
              Selected(isSelected: false.obs, name: "SE8".obs),
            ]).map((e) => e.toJson()).toList()));
        getDataListSavar.value = RxList<Selected>([
          Selected(isSelected: false.obs, name: "1".obs),
          Selected(isSelected: false.obs, name: "2".obs),
          Selected(isSelected: false.obs, name: "3".obs),
          Selected(isSelected: false.obs, name: "4".obs),
          Selected(isSelected: false.obs, name: "5".obs),
          Selected(isSelected: false.obs, name: "6".obs),
          Selected(isSelected: false.obs, name: "7".obs),
          Selected(isSelected: false.obs, name: "8".obs),
          Selected(isSelected: false.obs, name: "9".obs),
          Selected(isSelected: false.obs, name: "10".obs),
          Selected(isSelected: false.obs, name: "11".obs),
          Selected(isSelected: false.obs, name: "12".obs),
          Selected(isSelected: false.obs, name: "13".obs),
          Selected(isSelected: false.obs, name: "14".obs),
          Selected(isSelected: false.obs, name: "15".obs),
          Selected(isSelected: false.obs, name: "16".obs),
          Selected(isSelected: false.obs, name: "17".obs),
          Selected(isSelected: false.obs, name: "18".obs),
          Selected(isSelected: false.obs, name: "19".obs),
          Selected(isSelected: false.obs, name: "20".obs),
          Selected(isSelected: false.obs, name: "21".obs),
          Selected(isSelected: false.obs, name: "22".obs),
          Selected(isSelected: false.obs, name: "23".obs),
          Selected(isSelected: false.obs, name: "24".obs),
          Selected(isSelected: false.obs, name: "25".obs),
          Selected(isSelected: false.obs, name: "26".obs),
          Selected(isSelected: false.obs, name: "27".obs),
          Selected(isSelected: false.obs, name: "28".obs),
          Selected(isSelected: false.obs, name: "29".obs),
          Selected(isSelected: false.obs, name: "30".obs),
          Selected(isSelected: false.obs, name: "31".obs),
          Selected(isSelected: false.obs, name: "32".obs),
          Selected(isSelected: false.obs, name: "33".obs),
          Selected(isSelected: false.obs, name: "34".obs),
          Selected(isSelected: false.obs, name: "35".obs),
          Selected(isSelected: false.obs, name: "36".obs),
          Selected(isSelected: false.obs, name: "37".obs),
          Selected(isSelected: false.obs, name: "38".obs),
          Selected(isSelected: false.obs, name: "39".obs),
          Selected(isSelected: false.obs, name: "40".obs),
          Selected(isSelected: false.obs, name: "41".obs),
          Selected(isSelected: false.obs, name: "42".obs),
          Selected(isSelected: false.obs, name: "43".obs),
          Selected(isSelected: false.obs, name: "44".obs),
          Selected(isSelected: false.obs, name: "45".obs),
          Selected(isSelected: false.obs, name: "46".obs),
          Selected(isSelected: false.obs, name: "47".obs),
          Selected(isSelected: false.obs, name: "48".obs),
          Selected(isSelected: false.obs, name: "49".obs),
          Selected(isSelected: false.obs, name: "50".obs),
          Selected(isSelected: false.obs, name: "51".obs),
          Selected(isSelected: false.obs, name: "52".obs),
          Selected(isSelected: false.obs, name: "53".obs),
          Selected(isSelected: false.obs, name: "54".obs),
          Selected(isSelected: false.obs, name: "55".obs),
          Selected(isSelected: false.obs, name: "56".obs),
          Selected(isSelected: false.obs, name: "57".obs),
          Selected(isSelected: false.obs, name: "58".obs),
          Selected(isSelected: false.obs, name: "59".obs),
          Selected(isSelected: false.obs, name: "61".obs),
          Selected(isSelected: false.obs, name: "62".obs),
          Selected(isSelected: false.obs, name: "63".obs),
          Selected(isSelected: false.obs, name: "64".obs),
          Selected(isSelected: false.obs, name: "65".obs),
          Selected(isSelected: false.obs, name: "P1".obs),
          Selected(isSelected: false.obs, name: "P2".obs),
          Selected(isSelected: false.obs, name: "P3".obs),
          Selected(isSelected: false.obs, name: "P4".obs),
          Selected(isSelected: false.obs, name: "P5".obs),
          Selected(isSelected: false.obs, name: "P6".obs),
          Selected(isSelected: false.obs, name: "P7".obs),
          Selected(isSelected: false.obs, name: "P8".obs),
          Selected(isSelected: false.obs, name: "P9".obs),
          Selected(isSelected: false.obs, name: "P10".obs),
          Selected(isSelected: false.obs, name: "S1".obs),
          Selected(isSelected: false.obs, name: "S2".obs),
          Selected(isSelected: false.obs, name: "S3".obs),
          Selected(isSelected: false.obs, name: "S4".obs),
          Selected(isSelected: false.obs, name: "S5".obs),
          Selected(isSelected: false.obs, name: "S6".obs),
          Selected(isSelected: false.obs, name: "S7".obs),
          Selected(isSelected: false.obs, name: "S8".obs),
          Selected(isSelected: false.obs, name: "S9".obs),
          Selected(isSelected: false.obs, name: "S10".obs),
          Selected(isSelected: false.obs, name: "S11".obs),
          Selected(isSelected: false.obs, name: "S12".obs),
          Selected(isSelected: false.obs, name: "S13".obs),
          Selected(isSelected: false.obs, name: "S14".obs),
          Selected(isSelected: false.obs, name: "S15".obs),
          Selected(isSelected: false.obs, name: "S16".obs),
          Selected(isSelected: false.obs, name: "S17".obs),
          Selected(isSelected: false.obs, name: "M18".obs),
          Selected(isSelected: false.obs, name: "M19".obs),
          Selected(isSelected: false.obs, name: "M20".obs),
          Selected(isSelected: false.obs, name: "M21".obs),
          Selected(isSelected: false.obs, name: "M22".obs),
          Selected(isSelected: false.obs, name: "SE1".obs),
          Selected(isSelected: false.obs, name: "SE2".obs),
          Selected(isSelected: false.obs, name: "SE3".obs),
          Selected(isSelected: false.obs, name: "SE4".obs),
          Selected(isSelected: false.obs, name: "SE5".obs),
          Selected(isSelected: false.obs, name: "SE6".obs),
          Selected(isSelected: false.obs, name: "SE7".obs),
          Selected(isSelected: false.obs, name: "SE8".obs),
        ]);
      }
      if (!isNullEmptyOrFalse(box.read(selectedDataDate.value + "Sanj"))) {
        getDataListSanj.value =
            ((jsonDecode(box.read(selectedDataDate.value + "Sanj"))
                        as List<dynamic>)
                    .toList())
                .map((e) => Selected.fromJson(e))
                .toList();
      } else {
        box.write(
            selectedDataDate.value + "Sanj",
            jsonEncode(RxList<Selected>([
              Selected(isSelected: false.obs, name: "1".obs),
              Selected(isSelected: false.obs, name: "2".obs),
              Selected(isSelected: false.obs, name: "3".obs),
              Selected(isSelected: false.obs, name: "4".obs),
              Selected(isSelected: false.obs, name: "5".obs),
              Selected(isSelected: false.obs, name: "6".obs),
              Selected(isSelected: false.obs, name: "7".obs),
              Selected(isSelected: false.obs, name: "8".obs),
              Selected(isSelected: false.obs, name: "9".obs),
              Selected(isSelected: false.obs, name: "10".obs),
              Selected(isSelected: false.obs, name: "11".obs),
              Selected(isSelected: false.obs, name: "12".obs),
              Selected(isSelected: false.obs, name: "13".obs),
              Selected(isSelected: false.obs, name: "14".obs),
              Selected(isSelected: false.obs, name: "15".obs),
              Selected(isSelected: false.obs, name: "16".obs),
              Selected(isSelected: false.obs, name: "17".obs),
              Selected(isSelected: false.obs, name: "18".obs),
              Selected(isSelected: false.obs, name: "19".obs),
              Selected(isSelected: false.obs, name: "20".obs),
              Selected(isSelected: false.obs, name: "21".obs),
              Selected(isSelected: false.obs, name: "22".obs),
              Selected(isSelected: false.obs, name: "23".obs),
              Selected(isSelected: false.obs, name: "24".obs),
              Selected(isSelected: false.obs, name: "25".obs),
              Selected(isSelected: false.obs, name: "26".obs),
              Selected(isSelected: false.obs, name: "27".obs),
              Selected(isSelected: false.obs, name: "28".obs),
              Selected(isSelected: false.obs, name: "29".obs),
              Selected(isSelected: false.obs, name: "30".obs),
              Selected(isSelected: false.obs, name: "31".obs),
              Selected(isSelected: false.obs, name: "32".obs),
              Selected(isSelected: false.obs, name: "33".obs),
              Selected(isSelected: false.obs, name: "34".obs),
              Selected(isSelected: false.obs, name: "35".obs),
              Selected(isSelected: false.obs, name: "36".obs),
              Selected(isSelected: false.obs, name: "37".obs),
              Selected(isSelected: false.obs, name: "38".obs),
              Selected(isSelected: false.obs, name: "39".obs),
              Selected(isSelected: false.obs, name: "40".obs),
              Selected(isSelected: false.obs, name: "41".obs),
              Selected(isSelected: false.obs, name: "42".obs),
              Selected(isSelected: false.obs, name: "43".obs),
              Selected(isSelected: false.obs, name: "44".obs),
              Selected(isSelected: false.obs, name: "45".obs),
              Selected(isSelected: false.obs, name: "46".obs),
              Selected(isSelected: false.obs, name: "47".obs),
              Selected(isSelected: false.obs, name: "48".obs),
              Selected(isSelected: false.obs, name: "49".obs),
              Selected(isSelected: false.obs, name: "50".obs),
              Selected(isSelected: false.obs, name: "51".obs),
              Selected(isSelected: false.obs, name: "52".obs),
              Selected(isSelected: false.obs, name: "53".obs),
              Selected(isSelected: false.obs, name: "54".obs),
              Selected(isSelected: false.obs, name: "55".obs),
              Selected(isSelected: false.obs, name: "56".obs),
              Selected(isSelected: false.obs, name: "57".obs),
              Selected(isSelected: false.obs, name: "58".obs),
              Selected(isSelected: false.obs, name: "59".obs),
              Selected(isSelected: false.obs, name: "61".obs),
              Selected(isSelected: false.obs, name: "62".obs),
              Selected(isSelected: false.obs, name: "63".obs),
              Selected(isSelected: false.obs, name: "64".obs),
              Selected(isSelected: false.obs, name: "65".obs),
              Selected(isSelected: false.obs, name: "P1".obs),
              Selected(isSelected: false.obs, name: "P2".obs),
              Selected(isSelected: false.obs, name: "P3".obs),
              Selected(isSelected: false.obs, name: "P4".obs),
              Selected(isSelected: false.obs, name: "P5".obs),
              Selected(isSelected: false.obs, name: "P6".obs),
              Selected(isSelected: false.obs, name: "P7".obs),
              Selected(isSelected: false.obs, name: "P8".obs),
              Selected(isSelected: false.obs, name: "P9".obs),
              Selected(isSelected: false.obs, name: "P10".obs),
              Selected(isSelected: false.obs, name: "S1".obs),
              Selected(isSelected: false.obs, name: "S2".obs),
              Selected(isSelected: false.obs, name: "S3".obs),
              Selected(isSelected: false.obs, name: "S4".obs),
              Selected(isSelected: false.obs, name: "S5".obs),
              Selected(isSelected: false.obs, name: "S6".obs),
              Selected(isSelected: false.obs, name: "S7".obs),
              Selected(isSelected: false.obs, name: "S8".obs),
              Selected(isSelected: false.obs, name: "S9".obs),
              Selected(isSelected: false.obs, name: "S10".obs),
              Selected(isSelected: false.obs, name: "S11".obs),
              Selected(isSelected: false.obs, name: "S12".obs),
              Selected(isSelected: false.obs, name: "S13".obs),
              Selected(isSelected: false.obs, name: "S14".obs),
              Selected(isSelected: false.obs, name: "S15".obs),
              Selected(isSelected: false.obs, name: "S16".obs),
              Selected(isSelected: false.obs, name: "S17".obs),
              Selected(isSelected: false.obs, name: "M18".obs),
              Selected(isSelected: false.obs, name: "M19".obs),
              Selected(isSelected: false.obs, name: "M20".obs),
              Selected(isSelected: false.obs, name: "M21".obs),
              Selected(isSelected: false.obs, name: "M22".obs),
              Selected(isSelected: false.obs, name: "SE1".obs),
              Selected(isSelected: false.obs, name: "SE2".obs),
              Selected(isSelected: false.obs, name: "SE3".obs),
              Selected(isSelected: false.obs, name: "SE4".obs),
              Selected(isSelected: false.obs, name: "SE5".obs),
              Selected(isSelected: false.obs, name: "SE6".obs),
              Selected(isSelected: false.obs, name: "SE7".obs),
              Selected(isSelected: false.obs, name: "SE8".obs),
            ]).map((e) => e.toJson()).toList()));
        getDataListSanj.value = RxList<Selected>([
          Selected(isSelected: false.obs, name: "1".obs),
          Selected(isSelected: false.obs, name: "2".obs),
          Selected(isSelected: false.obs, name: "3".obs),
          Selected(isSelected: false.obs, name: "4".obs),
          Selected(isSelected: false.obs, name: "5".obs),
          Selected(isSelected: false.obs, name: "6".obs),
          Selected(isSelected: false.obs, name: "7".obs),
          Selected(isSelected: false.obs, name: "8".obs),
          Selected(isSelected: false.obs, name: "9".obs),
          Selected(isSelected: false.obs, name: "10".obs),
          Selected(isSelected: false.obs, name: "11".obs),
          Selected(isSelected: false.obs, name: "12".obs),
          Selected(isSelected: false.obs, name: "13".obs),
          Selected(isSelected: false.obs, name: "14".obs),
          Selected(isSelected: false.obs, name: "15".obs),
          Selected(isSelected: false.obs, name: "16".obs),
          Selected(isSelected: false.obs, name: "17".obs),
          Selected(isSelected: false.obs, name: "18".obs),
          Selected(isSelected: false.obs, name: "19".obs),
          Selected(isSelected: false.obs, name: "20".obs),
          Selected(isSelected: false.obs, name: "21".obs),
          Selected(isSelected: false.obs, name: "22".obs),
          Selected(isSelected: false.obs, name: "23".obs),
          Selected(isSelected: false.obs, name: "24".obs),
          Selected(isSelected: false.obs, name: "25".obs),
          Selected(isSelected: false.obs, name: "26".obs),
          Selected(isSelected: false.obs, name: "27".obs),
          Selected(isSelected: false.obs, name: "28".obs),
          Selected(isSelected: false.obs, name: "29".obs),
          Selected(isSelected: false.obs, name: "30".obs),
          Selected(isSelected: false.obs, name: "31".obs),
          Selected(isSelected: false.obs, name: "32".obs),
          Selected(isSelected: false.obs, name: "33".obs),
          Selected(isSelected: false.obs, name: "34".obs),
          Selected(isSelected: false.obs, name: "35".obs),
          Selected(isSelected: false.obs, name: "36".obs),
          Selected(isSelected: false.obs, name: "37".obs),
          Selected(isSelected: false.obs, name: "38".obs),
          Selected(isSelected: false.obs, name: "39".obs),
          Selected(isSelected: false.obs, name: "40".obs),
          Selected(isSelected: false.obs, name: "41".obs),
          Selected(isSelected: false.obs, name: "42".obs),
          Selected(isSelected: false.obs, name: "43".obs),
          Selected(isSelected: false.obs, name: "44".obs),
          Selected(isSelected: false.obs, name: "45".obs),
          Selected(isSelected: false.obs, name: "46".obs),
          Selected(isSelected: false.obs, name: "47".obs),
          Selected(isSelected: false.obs, name: "48".obs),
          Selected(isSelected: false.obs, name: "49".obs),
          Selected(isSelected: false.obs, name: "50".obs),
          Selected(isSelected: false.obs, name: "51".obs),
          Selected(isSelected: false.obs, name: "52".obs),
          Selected(isSelected: false.obs, name: "53".obs),
          Selected(isSelected: false.obs, name: "54".obs),
          Selected(isSelected: false.obs, name: "55".obs),
          Selected(isSelected: false.obs, name: "56".obs),
          Selected(isSelected: false.obs, name: "57".obs),
          Selected(isSelected: false.obs, name: "58".obs),
          Selected(isSelected: false.obs, name: "59".obs),
          Selected(isSelected: false.obs, name: "61".obs),
          Selected(isSelected: false.obs, name: "62".obs),
          Selected(isSelected: false.obs, name: "63".obs),
          Selected(isSelected: false.obs, name: "64".obs),
          Selected(isSelected: false.obs, name: "65".obs),
          Selected(isSelected: false.obs, name: "P1".obs),
          Selected(isSelected: false.obs, name: "P2".obs),
          Selected(isSelected: false.obs, name: "P3".obs),
          Selected(isSelected: false.obs, name: "P4".obs),
          Selected(isSelected: false.obs, name: "P5".obs),
          Selected(isSelected: false.obs, name: "P6".obs),
          Selected(isSelected: false.obs, name: "P7".obs),
          Selected(isSelected: false.obs, name: "P8".obs),
          Selected(isSelected: false.obs, name: "P9".obs),
          Selected(isSelected: false.obs, name: "P10".obs),
          Selected(isSelected: false.obs, name: "S1".obs),
          Selected(isSelected: false.obs, name: "S2".obs),
          Selected(isSelected: false.obs, name: "S3".obs),
          Selected(isSelected: false.obs, name: "S4".obs),
          Selected(isSelected: false.obs, name: "S5".obs),
          Selected(isSelected: false.obs, name: "S6".obs),
          Selected(isSelected: false.obs, name: "S7".obs),
          Selected(isSelected: false.obs, name: "S8".obs),
          Selected(isSelected: false.obs, name: "S9".obs),
          Selected(isSelected: false.obs, name: "S10".obs),
          Selected(isSelected: false.obs, name: "S11".obs),
          Selected(isSelected: false.obs, name: "S12".obs),
          Selected(isSelected: false.obs, name: "S13".obs),
          Selected(isSelected: false.obs, name: "S14".obs),
          Selected(isSelected: false.obs, name: "S15".obs),
          Selected(isSelected: false.obs, name: "S16".obs),
          Selected(isSelected: false.obs, name: "S17".obs),
          Selected(isSelected: false.obs, name: "M18".obs),
          Selected(isSelected: false.obs, name: "M19".obs),
          Selected(isSelected: false.obs, name: "M20".obs),
          Selected(isSelected: false.obs, name: "M21".obs),
          Selected(isSelected: false.obs, name: "M22".obs),
          Selected(isSelected: false.obs, name: "SE1".obs),
          Selected(isSelected: false.obs, name: "SE2".obs),
          Selected(isSelected: false.obs, name: "SE3".obs),
          Selected(isSelected: false.obs, name: "SE4".obs),
          Selected(isSelected: false.obs, name: "SE5".obs),
          Selected(isSelected: false.obs, name: "SE6".obs),
          Selected(isSelected: false.obs, name: "SE7".obs),
          Selected(isSelected: false.obs, name: "SE8".obs),
        ]);
      }
      for (int i = 0; i < getDataListSanj.length; i++) {
        if (getDataListSanj[i].isSelected.isFalse &&
            getDataListSavar[i].isSelected.isFalse) {
          list.add(getDataList[i].name.value);
        }
      }
    } else {
      if (!isNullEmptyOrFalse(
          box.read(selectedDataDate.value + getSelectedText()))) {
        getDataList.value =
            ((jsonDecode(box.read(selectedDataDate.value + getSelectedText()))
                        as List<dynamic>)
                    .toList())
                .map((e) => Selected.fromJson(e))
                .toList();

        if (!isNullEmptyOrFalse(getDataList)) {
          for (int i = 0; i < getDataList.length; i++) {
            if (getDataList[i].isSelected.isFalse) {
              list.add(getDataList[i].name.value);
            }
          }
        }
      } else {
        box.write(selectedDataDate.value + getSelectedText(),
            jsonEncode(RxList<Selected>([
              Selected(isSelected: false.obs, name: "1".obs),
              Selected(isSelected: false.obs, name: "2".obs),
              Selected(isSelected: false.obs, name: "3".obs),
              Selected(isSelected: false.obs, name: "4".obs),
              Selected(isSelected: false.obs, name: "5".obs),
              Selected(isSelected: false.obs, name: "6".obs),
              Selected(isSelected: false.obs, name: "7".obs),
              Selected(isSelected: false.obs, name: "8".obs),
              Selected(isSelected: false.obs, name: "9".obs),
              Selected(isSelected: false.obs, name: "10".obs),
              Selected(isSelected: false.obs, name: "11".obs),
              Selected(isSelected: false.obs, name: "12".obs),
              Selected(isSelected: false.obs, name: "13".obs),
              Selected(isSelected: false.obs, name: "14".obs),
              Selected(isSelected: false.obs, name: "15".obs),
              Selected(isSelected: false.obs, name: "16".obs),
              Selected(isSelected: false.obs, name: "17".obs),
              Selected(isSelected: false.obs, name: "18".obs),
              Selected(isSelected: false.obs, name: "19".obs),
              Selected(isSelected: false.obs, name: "20".obs),
              Selected(isSelected: false.obs, name: "21".obs),
              Selected(isSelected: false.obs, name: "22".obs),
              Selected(isSelected: false.obs, name: "23".obs),
              Selected(isSelected: false.obs, name: "24".obs),
              Selected(isSelected: false.obs, name: "25".obs),
              Selected(isSelected: false.obs, name: "26".obs),
              Selected(isSelected: false.obs, name: "27".obs),
              Selected(isSelected: false.obs, name: "28".obs),
              Selected(isSelected: false.obs, name: "29".obs),
              Selected(isSelected: false.obs, name: "30".obs),
              Selected(isSelected: false.obs, name: "31".obs),
              Selected(isSelected: false.obs, name: "32".obs),
              Selected(isSelected: false.obs, name: "33".obs),
              Selected(isSelected: false.obs, name: "34".obs),
              Selected(isSelected: false.obs, name: "35".obs),
              Selected(isSelected: false.obs, name: "36".obs),
              Selected(isSelected: false.obs, name: "37".obs),
              Selected(isSelected: false.obs, name: "38".obs),
              Selected(isSelected: false.obs, name: "39".obs),
              Selected(isSelected: false.obs, name: "40".obs),
              Selected(isSelected: false.obs, name: "41".obs),
              Selected(isSelected: false.obs, name: "42".obs),
              Selected(isSelected: false.obs, name: "43".obs),
              Selected(isSelected: false.obs, name: "44".obs),
              Selected(isSelected: false.obs, name: "45".obs),
              Selected(isSelected: false.obs, name: "46".obs),
              Selected(isSelected: false.obs, name: "47".obs),
              Selected(isSelected: false.obs, name: "48".obs),
              Selected(isSelected: false.obs, name: "49".obs),
              Selected(isSelected: false.obs, name: "50".obs),
              Selected(isSelected: false.obs, name: "51".obs),
              Selected(isSelected: false.obs, name: "52".obs),
              Selected(isSelected: false.obs, name: "53".obs),
              Selected(isSelected: false.obs, name: "54".obs),
              Selected(isSelected: false.obs, name: "55".obs),
              Selected(isSelected: false.obs, name: "56".obs),
              Selected(isSelected: false.obs, name: "57".obs),
              Selected(isSelected: false.obs, name: "58".obs),
              Selected(isSelected: false.obs, name: "59".obs),
              Selected(isSelected: false.obs, name: "61".obs),
              Selected(isSelected: false.obs, name: "62".obs),
              Selected(isSelected: false.obs, name: "63".obs),
              Selected(isSelected: false.obs, name: "64".obs),
              Selected(isSelected: false.obs, name: "65".obs),
              Selected(isSelected: false.obs, name: "P1".obs),
              Selected(isSelected: false.obs, name: "P2".obs),
              Selected(isSelected: false.obs, name: "P3".obs),
              Selected(isSelected: false.obs, name: "P4".obs),
              Selected(isSelected: false.obs, name: "P5".obs),
              Selected(isSelected: false.obs, name: "P6".obs),
              Selected(isSelected: false.obs, name: "P7".obs),
              Selected(isSelected: false.obs, name: "P8".obs),
              Selected(isSelected: false.obs, name: "P9".obs),
              Selected(isSelected: false.obs, name: "P10".obs),
              Selected(isSelected: false.obs, name: "S1".obs),
              Selected(isSelected: false.obs, name: "S2".obs),
              Selected(isSelected: false.obs, name: "S3".obs),
              Selected(isSelected: false.obs, name: "S4".obs),
              Selected(isSelected: false.obs, name: "S5".obs),
              Selected(isSelected: false.obs, name: "S6".obs),
              Selected(isSelected: false.obs, name: "S7".obs),
              Selected(isSelected: false.obs, name: "S8".obs),
              Selected(isSelected: false.obs, name: "S9".obs),
              Selected(isSelected: false.obs, name: "S10".obs),
              Selected(isSelected: false.obs, name: "S11".obs),
              Selected(isSelected: false.obs, name: "S12".obs),
              Selected(isSelected: false.obs, name: "S13".obs),
              Selected(isSelected: false.obs, name: "S14".obs),
              Selected(isSelected: false.obs, name: "S15".obs),
              Selected(isSelected: false.obs, name: "S16".obs),
              Selected(isSelected: false.obs, name: "S17".obs),
              Selected(isSelected: false.obs, name: "M18".obs),
              Selected(isSelected: false.obs, name: "M19".obs),
              Selected(isSelected: false.obs, name: "M20".obs),
              Selected(isSelected: false.obs, name: "M21".obs),
              Selected(isSelected: false.obs, name: "M22".obs),
              Selected(isSelected: false.obs, name: "SE1".obs),
              Selected(isSelected: false.obs, name: "SE2".obs),
              Selected(isSelected: false.obs, name: "SE3".obs),
              Selected(isSelected: false.obs, name: "SE4".obs),
              Selected(isSelected: false.obs, name: "SE5".obs),
              Selected(isSelected: false.obs, name: "SE6".obs),
              Selected(isSelected: false.obs, name: "SE7".obs),
              Selected(isSelected: false.obs, name: "SE8".obs),
            ]).map((e) => e.name.value).toList()));
        list.clear();

        list.addAll([

          Selected(isSelected: false.obs, name: "1".obs),
          Selected(isSelected: false.obs, name: "2".obs),
          Selected(isSelected: false.obs, name: "3".obs),
          Selected(isSelected: false.obs, name: "4".obs),
          Selected(isSelected: false.obs, name: "5".obs),
          Selected(isSelected: false.obs, name: "6".obs),
          Selected(isSelected: false.obs, name: "7".obs),
          Selected(isSelected: false.obs, name: "8".obs),
          Selected(isSelected: false.obs, name: "9".obs),
          Selected(isSelected: false.obs, name: "10".obs),
          Selected(isSelected: false.obs, name: "11".obs),
          Selected(isSelected: false.obs, name: "12".obs),
          Selected(isSelected: false.obs, name: "13".obs),
          Selected(isSelected: false.obs, name: "14".obs),
          Selected(isSelected: false.obs, name: "15".obs),
          Selected(isSelected: false.obs, name: "16".obs),
          Selected(isSelected: false.obs, name: "17".obs),
          Selected(isSelected: false.obs, name: "18".obs),
          Selected(isSelected: false.obs, name: "19".obs),
          Selected(isSelected: false.obs, name: "20".obs),
          Selected(isSelected: false.obs, name: "21".obs),
          Selected(isSelected: false.obs, name: "22".obs),
          Selected(isSelected: false.obs, name: "23".obs),
          Selected(isSelected: false.obs, name: "24".obs),
          Selected(isSelected: false.obs, name: "25".obs),
          Selected(isSelected: false.obs, name: "26".obs),
          Selected(isSelected: false.obs, name: "27".obs),
          Selected(isSelected: false.obs, name: "28".obs),
          Selected(isSelected: false.obs, name: "29".obs),
          Selected(isSelected: false.obs, name: "30".obs),
          Selected(isSelected: false.obs, name: "31".obs),
          Selected(isSelected: false.obs, name: "32".obs),
          Selected(isSelected: false.obs, name: "33".obs),
          Selected(isSelected: false.obs, name: "34".obs),
          Selected(isSelected: false.obs, name: "35".obs),
          Selected(isSelected: false.obs, name: "36".obs),
          Selected(isSelected: false.obs, name: "37".obs),
          Selected(isSelected: false.obs, name: "38".obs),
          Selected(isSelected: false.obs, name: "39".obs),
          Selected(isSelected: false.obs, name: "40".obs),
          Selected(isSelected: false.obs, name: "41".obs),
          Selected(isSelected: false.obs, name: "42".obs),
          Selected(isSelected: false.obs, name: "43".obs),
          Selected(isSelected: false.obs, name: "44".obs),
          Selected(isSelected: false.obs, name: "45".obs),
          Selected(isSelected: false.obs, name: "46".obs),
          Selected(isSelected: false.obs, name: "47".obs),
          Selected(isSelected: false.obs, name: "48".obs),
          Selected(isSelected: false.obs, name: "49".obs),
          Selected(isSelected: false.obs, name: "50".obs),
          Selected(isSelected: false.obs, name: "51".obs),
          Selected(isSelected: false.obs, name: "52".obs),
          Selected(isSelected: false.obs, name: "53".obs),
          Selected(isSelected: false.obs, name: "54".obs),
          Selected(isSelected: false.obs, name: "55".obs),
          Selected(isSelected: false.obs, name: "56".obs),
          Selected(isSelected: false.obs, name: "57".obs),
          Selected(isSelected: false.obs, name: "58".obs),
          Selected(isSelected: false.obs, name: "59".obs),
          Selected(isSelected: false.obs, name: "61".obs),
          Selected(isSelected: false.obs, name: "62".obs),
          Selected(isSelected: false.obs, name: "63".obs),
          Selected(isSelected: false.obs, name: "64".obs),
          Selected(isSelected: false.obs, name: "65".obs),
          Selected(isSelected: false.obs, name: "P1".obs),
          Selected(isSelected: false.obs, name: "P2".obs),
          Selected(isSelected: false.obs, name: "P3".obs),
          Selected(isSelected: false.obs, name: "P4".obs),
          Selected(isSelected: false.obs, name: "P5".obs),
          Selected(isSelected: false.obs, name: "P6".obs),
          Selected(isSelected: false.obs, name: "P7".obs),
          Selected(isSelected: false.obs, name: "P8".obs),
          Selected(isSelected: false.obs, name: "P9".obs),
          Selected(isSelected: false.obs, name: "P10".obs),
          Selected(isSelected: false.obs, name: "S1".obs),
          Selected(isSelected: false.obs, name: "S2".obs),
          Selected(isSelected: false.obs, name: "S3".obs),
          Selected(isSelected: false.obs, name: "S4".obs),
          Selected(isSelected: false.obs, name: "S5".obs),
          Selected(isSelected: false.obs, name: "S6".obs),
          Selected(isSelected: false.obs, name: "S7".obs),
          Selected(isSelected: false.obs, name: "S8".obs),
          Selected(isSelected: false.obs, name: "S9".obs),
          Selected(isSelected: false.obs, name: "S10".obs),
          Selected(isSelected: false.obs, name: "S11".obs),
          Selected(isSelected: false.obs, name: "S12".obs),
          Selected(isSelected: false.obs, name: "S13".obs),
          Selected(isSelected: false.obs, name: "S14".obs),
          Selected(isSelected: false.obs, name: "S15".obs),
          Selected(isSelected: false.obs, name: "S16".obs),
          Selected(isSelected: false.obs, name: "S17".obs),
          Selected(isSelected: false.obs, name: "M18".obs),
          Selected(isSelected: false.obs, name: "M19".obs),
          Selected(isSelected: false.obs, name: "M20".obs),
          Selected(isSelected: false.obs, name: "M21".obs),
          Selected(isSelected: false.obs, name: "M22".obs),
          Selected(isSelected: false.obs, name: "SE1".obs),
          Selected(isSelected: false.obs, name: "SE2".obs),
          Selected(isSelected: false.obs, name: "SE3".obs),
          Selected(isSelected: false.obs, name: "SE4".obs),
          Selected(isSelected: false.obs, name: "SE5".obs),
          Selected(isSelected: false.obs, name: "SE6".obs),
          Selected(isSelected: false.obs, name: "SE7".obs),
          Selected(isSelected: false.obs, name: "SE8".obs),
        ].map((e) => e.name.value).toList());
      }
    }

    dropdownValue.value = list.first.toString();
    hasData.value = true;
  }

  datePick({required BuildContext context}) async {
    DateTime? pickedDate = await showDatePicker(
        context: context,
        initialDate: DateTime.now(),
        firstDate: DateTime(1950),
        lastDate: DateTime(2100));
    if (pickedDate != null) {
      print(pickedDate);
      selectedDate.value = DateFormat('dd/MM/yyyy').format(pickedDate);
      selectedDataDate.value = DateFormat('dd/MM/yyyy').format(pickedDate);
      data();
    } else {}
  }

  getSelectedText() {
    if (isFullDaySelected.isTrue) {
      return "Full";
    } else if (isSavarSelected.isTrue) {
      return "Savar";
    } else if (isSanjSelected.isTrue) {
      return "Sanj";
    }
    return "Savar";
  }

  @override
  void onReady() {
    super.onReady();
  }

  @override
  void onClose() {
    super.onClose();
  }
}
