import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutterotp_firebase/app/Constant/app_constant.dart';
import 'package:flutterotp_firebase/app/Constant/sizeConstant.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';

import '../../../../../main.dart';
import '../../Home/controller/Selectedmodel.dart';

class AddUpvasController extends GetxController {
  RxString selectedDate = "".obs;
  RxBool isSavarSelected = true.obs;
  RxBool isSanjSelected = false.obs;
  RxBool isFullDaySelected = false.obs;
  RxBool hasData = false.obs;
  RxList<Selected>  getDataList = RxList<Selected>([]);
  RxList<String> list = RxList<String>([]);
  RxString dropdownValue = "1".obs;
  RxString DataDate = "".obs;

  @override
  void onInit() {
    selectedDate.value =
        DateFormat('dd MMM, yyyy').format(DateTime.now()).toString();
    DataDate.value = DateFormat('dd/MM/yyyy').format(DateTime.now()).toString();
    data();
    super.onInit();
  }

  data({String text = "savar"}) async {
    hasData.value = false;
    list.clear();
    await Future.delayed(Duration(milliseconds: 50));
    if (getSelectedText() == timeConstant.full) {
      RxList<Selected> getDataListSavar = RxList<Selected>([]);
      RxList<Selected> getDataListSanj = RxList<Selected>([]);
      if (!isNullEmptyOrFalse(box.read(DataDate.value + timeConstant.savar))) {
        getDataListSavar.value =
            ((jsonDecode(box.read(DataDate.value + timeConstant.savar))
                        as List<dynamic>)
                    .toList())
                .map((e) => Selected.fromJson(e))
                .toList();
      } else {
        box.write(
            DataDate.value + timeConstant.savar,
            jsonEncode(RxList<Selected>([
              Selected(status: 0.obs, name: "1"),
              Selected(status: 0.obs, name: "2"),
              Selected(status: 0.obs, name: "3"),
              Selected(status: 0.obs, name: "4"),
              Selected(status: 0.obs, name: "5"),
              Selected(status: 0.obs, name: "6"),
              Selected(status: 0.obs, name: "7"),
              Selected(status: 0.obs, name: "8"),
              Selected(status: 0.obs, name: "9"),
              Selected(status: 0.obs, name: "10"),
              Selected(status: 0.obs, name: "11"),
              Selected(status: 0.obs, name: "12"),
              Selected(status: 0.obs, name: "13"),
              Selected(status: 0.obs, name: "14"),
              Selected(status: 0.obs, name: "15"),
              Selected(status: 0.obs, name: "16"),
              Selected(status: 0.obs, name: "17"),
              Selected(status: 0.obs, name: "18"),
              Selected(status: 0.obs, name: "19"),
              Selected(status: 0.obs, name: "20"),
              Selected(status: 0.obs, name: "21"),
              Selected(status: 0.obs, name: "22"),
              Selected(status: 0.obs, name: "23"),
              Selected(status: 0.obs, name: "24"),
              Selected(status: 0.obs, name: "25"),
              Selected(status: 0.obs, name: "26"),
              Selected(status: 0.obs, name: "27"),
              Selected(status: 0.obs, name: "28"),
              Selected(status: 0.obs, name: "29"),
              Selected(status: 0.obs, name: "30"),
              Selected(status: 0.obs, name: "31"),
              Selected(status: 0.obs, name: "32"),
              Selected(status: 0.obs, name: "33"),
              Selected(status: 0.obs, name: "34"),
              Selected(status: 0.obs, name: "35"),
              Selected(status: 0.obs, name: "36"),
              Selected(status: 0.obs, name: "37"),
              Selected(status: 0.obs, name: "38"),
              Selected(status: 0.obs, name: "39"),
              Selected(status: 0.obs, name: "40"),
              Selected(status: 0.obs, name: "41"),
              Selected(status: 0.obs, name: "42"),
              Selected(status: 0.obs, name: "43"),
              Selected(status: 0.obs, name: "44"),
              Selected(status: 0.obs, name: "45"),
              Selected(status: 0.obs, name: "46"),
              Selected(status: 0.obs, name: "47"),
              Selected(status: 0.obs, name: "48"),
              Selected(status: 0.obs, name: "49"),
              Selected(status: 0.obs, name: "50"),
              Selected(status: 0.obs, name: "51"),
              Selected(status: 0.obs, name: "52"),
              Selected(status: 0.obs, name: "53"),
              Selected(status: 0.obs, name: "54"),
              Selected(status: 0.obs, name: "55"),
              Selected(status: 0.obs, name: "56"),
              Selected(status: 0.obs, name: "57"),
              Selected(status: 0.obs, name: "58"),
              Selected(status: 0.obs, name: "59"),
              Selected(status: 0.obs, name: "60"),
              Selected(status: 0.obs, name: "61"),
              Selected(status: 0.obs, name: "62"),
              Selected(status: 0.obs, name: "63"),
              Selected(status: 0.obs, name: "64"),
              Selected(status: 0.obs, name: "65"),
              Selected(status: 0.obs, name: "P1"),
              Selected(status: 0.obs, name: "P2"),
              Selected(status: 0.obs, name: "P3"),
              Selected(status: 0.obs, name: "P4"),
              Selected(status: 0.obs, name: "P5"),
              Selected(status: 0.obs, name: "P6"),
              Selected(status: 0.obs, name: "P7"),
              Selected(status: 0.obs, name: "P8"),
              Selected(status: 0.obs, name: "P9"),
              Selected(status: 0.obs, name: "P10s"),
              Selected(status: 0.obs, name: "S1"),
              Selected(status: 0.obs, name: "S2"),
              Selected(status: 0.obs, name: "S3"),
              Selected(status: 0.obs, name: "S4"),
              Selected(status: 0.obs, name: "S5"),
              Selected(status: 0.obs, name: "S6"),
              Selected(status: 0.obs, name: "S7"),
              Selected(status: 0.obs, name: "S8"),
              Selected(status: 0.obs, name: "S9"),
              Selected(status: 0.obs, name: "S10"),
              Selected(status: 0.obs, name: "S11"),
              Selected(status: 0.obs, name: "S12"),
              Selected(status: 0.obs, name: "S13"),
              Selected(status: 0.obs, name: "S14"),
              Selected(status: 0.obs, name: "S15"),
              Selected(status: 0.obs, name: "S16"),
              Selected(status: 0.obs, name: "S17"),
              Selected(status: 0.obs, name: "M18"),
              Selected(status: 0.obs, name: "M19"),
              Selected(status: 0.obs, name: "M20"),
              Selected(status: 0.obs, name: "M21"),
              Selected(status: 0.obs, name: "M22"),
              Selected(status: 0.obs, name: "SE1"),
              Selected(status: 0.obs, name: "SE2"),
              Selected(status: 0.obs, name: "SE3"),
              Selected(status: 0.obs, name: "SE4"),
              Selected(status: 0.obs, name: "SE5"),
              Selected(status: 0.obs, name: "SE6"),
              Selected(status: 0.obs, name: "SE7"),
              Selected(status: 0.obs, name: "SE8"),
            ]).map((e) => e.toJson()).toList()));
        getDataListSavar.value = RxList<Selected>([
          Selected(status: 0.obs, name: "1"),
          Selected(status: 0.obs, name: "2"),
          Selected(status: 0.obs, name: "3"),
          Selected(status: 0.obs, name: "4"),
          Selected(status: 0.obs, name: "5"),
          Selected(status: 0.obs, name: "6"),
          Selected(status: 0.obs, name: "7"),
          Selected(status: 0.obs, name: "8"),
          Selected(status: 0.obs, name: "9"),
          Selected(status: 0.obs, name: "10"),
          Selected(status: 0.obs, name: "11"),
          Selected(status: 0.obs, name: "12"),
          Selected(status: 0.obs, name: "13"),
          Selected(status: 0.obs, name: "14"),
          Selected(status: 0.obs, name: "15"),
          Selected(status: 0.obs, name: "16"),
          Selected(status: 0.obs, name: "17"),
          Selected(status: 0.obs, name: "18"),
          Selected(status: 0.obs, name: "19"),
          Selected(status: 0.obs, name: "20"),
          Selected(status: 0.obs, name: "21"),
          Selected(status: 0.obs, name: "22"),
          Selected(status: 0.obs, name: "23"),
          Selected(status: 0.obs, name: "24"),
          Selected(status: 0.obs, name: "25"),
          Selected(status: 0.obs, name: "26"),
          Selected(status: 0.obs, name: "27"),
          Selected(status: 0.obs, name: "28"),
          Selected(status: 0.obs, name: "29"),
          Selected(status: 0.obs, name: "30"),
          Selected(status: 0.obs, name: "31"),
          Selected(status: 0.obs, name: "32"),
          Selected(status: 0.obs, name: "33"),
          Selected(status: 0.obs, name: "34"),
          Selected(status: 0.obs, name: "35"),
          Selected(status: 0.obs, name: "36"),
          Selected(status: 0.obs, name: "37"),
          Selected(status: 0.obs, name: "38"),
          Selected(status: 0.obs, name: "39"),
          Selected(status: 0.obs, name: "40"),
          Selected(status: 0.obs, name: "41"),
          Selected(status: 0.obs, name: "42"),
          Selected(status: 0.obs, name: "43"),
          Selected(status: 0.obs, name: "44"),
          Selected(status: 0.obs, name: "45"),
          Selected(status: 0.obs, name: "46"),
          Selected(status: 0.obs, name: "47"),
          Selected(status: 0.obs, name: "48"),
          Selected(status: 0.obs, name: "49"),
          Selected(status: 0.obs, name: "50"),
          Selected(status: 0.obs, name: "51"),
          Selected(status: 0.obs, name: "52"),
          Selected(status: 0.obs, name: "53"),
          Selected(status: 0.obs, name: "54"),
          Selected(status: 0.obs, name: "55"),
          Selected(status: 0.obs, name: "56"),
          Selected(status: 0.obs, name: "57"),
          Selected(status: 0.obs, name: "58"),
          Selected(status: 0.obs, name: "59"),
          Selected(status: 0.obs, name: "60"),
          Selected(status: 0.obs, name: "61"),
          Selected(status: 0.obs, name: "62"),
          Selected(status: 0.obs, name: "63"),
          Selected(status: 0.obs, name: "64"),
          Selected(status: 0.obs, name: "65"),
          Selected(status: 0.obs, name: "P1"),
          Selected(status: 0.obs, name: "P2"),
          Selected(status: 0.obs, name: "P3"),
          Selected(status: 0.obs, name: "P4"),
          Selected(status: 0.obs, name: "P5"),
          Selected(status: 0.obs, name: "P6"),
          Selected(status: 0.obs, name: "P7"),
          Selected(status: 0.obs, name: "P8"),
          Selected(status: 0.obs, name: "P9"),
          Selected(status: 0.obs, name: "P10s"),
          Selected(status: 0.obs, name: "S1"),
          Selected(status: 0.obs, name: "S2"),
          Selected(status: 0.obs, name: "S3"),
          Selected(status: 0.obs, name: "S4"),
          Selected(status: 0.obs, name: "S5"),
          Selected(status: 0.obs, name: "S6"),
          Selected(status: 0.obs, name: "S7"),
          Selected(status: 0.obs, name: "S8"),
          Selected(status: 0.obs, name: "S9"),
          Selected(status: 0.obs, name: "S10"),
          Selected(status: 0.obs, name: "S11"),
          Selected(status: 0.obs, name: "S12"),
          Selected(status: 0.obs, name: "S13"),
          Selected(status: 0.obs, name: "S14"),
          Selected(status: 0.obs, name: "S15"),
          Selected(status: 0.obs, name: "S16"),
          Selected(status: 0.obs, name: "S17"),
          Selected(status: 0.obs, name: "M18"),
          Selected(status: 0.obs, name: "M19"),
          Selected(status: 0.obs, name: "M20"),
          Selected(status: 0.obs, name: "M21"),
          Selected(status: 0.obs, name: "M22"),
          Selected(status: 0.obs, name: "SE1"),
          Selected(status: 0.obs, name: "SE2"),
          Selected(status: 0.obs, name: "SE3"),
          Selected(status: 0.obs, name: "SE4"),
          Selected(status: 0.obs, name: "SE5"),
          Selected(status: 0.obs, name: "SE6"),
          Selected(status: 0.obs, name: "SE7"),
          Selected(status: 0.obs, name: "SE8"),
        ]);
      }
      if (!isNullEmptyOrFalse(box.read(DataDate.value + timeConstant.Sanj))) {
        getDataListSanj.value =
            ((jsonDecode(box.read(DataDate.value + timeConstant.Sanj))
                        as List<dynamic>)
                    .toList())
                .map((e) => Selected.fromJson(e))
                .toList();
      } else {
        box.write(
            DataDate.value + timeConstant.Sanj,
            jsonEncode(RxList<Selected>([
              Selected(status: 0.obs, name: "1"),
              Selected(status: 0.obs, name: "2"),
              Selected(status: 0.obs, name: "3"),
              Selected(status: 0.obs, name: "4"),
              Selected(status: 0.obs, name: "5"),
              Selected(status: 0.obs, name: "6"),
              Selected(status: 0.obs, name: "7"),
              Selected(status: 0.obs, name: "8"),
              Selected(status: 0.obs, name: "9"),
              Selected(status: 0.obs, name: "10"),
              Selected(status: 0.obs, name: "11"),
              Selected(status: 0.obs, name: "12"),
              Selected(status: 0.obs, name: "13"),
              Selected(status: 0.obs, name: "14"),
              Selected(status: 0.obs, name: "15"),
              Selected(status: 0.obs, name: "16"),
              Selected(status: 0.obs, name: "17"),
              Selected(status: 0.obs, name: "18"),
              Selected(status: 0.obs, name: "19"),
              Selected(status: 0.obs, name: "20"),
              Selected(status: 0.obs, name: "21"),
              Selected(status: 0.obs, name: "22"),
              Selected(status: 0.obs, name: "23"),
              Selected(status: 0.obs, name: "24"),
              Selected(status: 0.obs, name: "25"),
              Selected(status: 0.obs, name: "26"),
              Selected(status: 0.obs, name: "27"),
              Selected(status: 0.obs, name: "28"),
              Selected(status: 0.obs, name: "29"),
              Selected(status: 0.obs, name: "30"),
              Selected(status: 0.obs, name: "31"),
              Selected(status: 0.obs, name: "32"),
              Selected(status: 0.obs, name: "33"),
              Selected(status: 0.obs, name: "34"),
              Selected(status: 0.obs, name: "35"),
              Selected(status: 0.obs, name: "36"),
              Selected(status: 0.obs, name: "37"),
              Selected(status: 0.obs, name: "38"),
              Selected(status: 0.obs, name: "39"),
              Selected(status: 0.obs, name: "40"),
              Selected(status: 0.obs, name: "41"),
              Selected(status: 0.obs, name: "42"),
              Selected(status: 0.obs, name: "43"),
              Selected(status: 0.obs, name: "44"),
              Selected(status: 0.obs, name: "45"),
              Selected(status: 0.obs, name: "46"),
              Selected(status: 0.obs, name: "47"),
              Selected(status: 0.obs, name: "48"),
              Selected(status: 0.obs, name: "49"),
              Selected(status: 0.obs, name: "50"),
              Selected(status: 0.obs, name: "51"),
              Selected(status: 0.obs, name: "52"),
              Selected(status: 0.obs, name: "53"),
              Selected(status: 0.obs, name: "54"),
              Selected(status: 0.obs, name: "55"),
              Selected(status: 0.obs, name: "56"),
              Selected(status: 0.obs, name: "57"),
              Selected(status: 0.obs, name: "58"),
              Selected(status: 0.obs, name: "59"),
              Selected(status: 0.obs, name: "60"),
              Selected(status: 0.obs, name: "61"),
              Selected(status: 0.obs, name: "62"),
              Selected(status: 0.obs, name: "63"),
              Selected(status: 0.obs, name: "64"),
              Selected(status: 0.obs, name: "65"),
              Selected(status: 0.obs, name: "P1"),
              Selected(status: 0.obs, name: "P2"),
              Selected(status: 0.obs, name: "P3"),
              Selected(status: 0.obs, name: "P4"),
              Selected(status: 0.obs, name: "P5"),
              Selected(status: 0.obs, name: "P6"),
              Selected(status: 0.obs, name: "P7"),
              Selected(status: 0.obs, name: "P8"),
              Selected(status: 0.obs, name: "P9"),
              Selected(status: 0.obs, name: "P10s"),
              Selected(status: 0.obs, name: "S1"),
              Selected(status: 0.obs, name: "S2"),
              Selected(status: 0.obs, name: "S3"),
              Selected(status: 0.obs, name: "S4"),
              Selected(status: 0.obs, name: "S5"),
              Selected(status: 0.obs, name: "S6"),
              Selected(status: 0.obs, name: "S7"),
              Selected(status: 0.obs, name: "S8"),
              Selected(status: 0.obs, name: "S9"),
              Selected(status: 0.obs, name: "S10"),
              Selected(status: 0.obs, name: "S11"),
              Selected(status: 0.obs, name: "S12"),
              Selected(status: 0.obs, name: "S13"),
              Selected(status: 0.obs, name: "S14"),
              Selected(status: 0.obs, name: "S15"),
              Selected(status: 0.obs, name: "S16"),
              Selected(status: 0.obs, name: "S17"),
              Selected(status: 0.obs, name: "M18"),
              Selected(status: 0.obs, name: "M19"),
              Selected(status: 0.obs, name: "M20"),
              Selected(status: 0.obs, name: "M21"),
              Selected(status: 0.obs, name: "M22"),
              Selected(status: 0.obs, name: "SE1"),
              Selected(status: 0.obs, name: "SE2"),
              Selected(status: 0.obs, name: "SE3"),
              Selected(status: 0.obs, name: "SE4"),
              Selected(status: 0.obs, name: "SE5"),
              Selected(status: 0.obs, name: "SE6"),
              Selected(status: 0.obs, name: "SE7"),
              Selected(status: 0.obs, name: "SE8"),
            ]).map((e) => e.toJson()).toList()));
        getDataListSanj.value = RxList<Selected>([
          Selected(status: 0.obs, name: "1"),
          Selected(status: 0.obs, name: "2"),
          Selected(status: 0.obs, name: "3"),
          Selected(status: 0.obs, name: "4"),
          Selected(status: 0.obs, name: "5"),
          Selected(status: 0.obs, name: "6"),
          Selected(status: 0.obs, name: "7"),
          Selected(status: 0.obs, name: "8"),
          Selected(status: 0.obs, name: "9"),
          Selected(status: 0.obs, name: "10"),
          Selected(status: 0.obs, name: "11"),
          Selected(status: 0.obs, name: "12"),
          Selected(status: 0.obs, name: "13"),
          Selected(status: 0.obs, name: "14"),
          Selected(status: 0.obs, name: "15"),
          Selected(status: 0.obs, name: "16"),
          Selected(status: 0.obs, name: "17"),
          Selected(status: 0.obs, name: "18"),
          Selected(status: 0.obs, name: "19"),
          Selected(status: 0.obs, name: "20"),
          Selected(status: 0.obs, name: "21"),
          Selected(status: 0.obs, name: "22"),
          Selected(status: 0.obs, name: "23"),
          Selected(status: 0.obs, name: "24"),
          Selected(status: 0.obs, name: "25"),
          Selected(status: 0.obs, name: "26"),
          Selected(status: 0.obs, name: "27"),
          Selected(status: 0.obs, name: "28"),
          Selected(status: 0.obs, name: "29"),
          Selected(status: 0.obs, name: "30"),
          Selected(status: 0.obs, name: "31"),
          Selected(status: 0.obs, name: "32"),
          Selected(status: 0.obs, name: "33"),
          Selected(status: 0.obs, name: "34"),
          Selected(status: 0.obs, name: "35"),
          Selected(status: 0.obs, name: "36"),
          Selected(status: 0.obs, name: "37"),
          Selected(status: 0.obs, name: "38"),
          Selected(status: 0.obs, name: "39"),
          Selected(status: 0.obs, name: "40"),
          Selected(status: 0.obs, name: "41"),
          Selected(status: 0.obs, name: "42"),
          Selected(status: 0.obs, name: "43"),
          Selected(status: 0.obs, name: "44"),
          Selected(status: 0.obs, name: "45"),
          Selected(status: 0.obs, name: "46"),
          Selected(status: 0.obs, name: "47"),
          Selected(status: 0.obs, name: "48"),
          Selected(status: 0.obs, name: "49"),
          Selected(status: 0.obs, name: "50"),
          Selected(status: 0.obs, name: "51"),
          Selected(status: 0.obs, name: "52"),
          Selected(status: 0.obs, name: "53"),
          Selected(status: 0.obs, name: "54"),
          Selected(status: 0.obs, name: "55"),
          Selected(status: 0.obs, name: "56"),
          Selected(status: 0.obs, name: "57"),
          Selected(status: 0.obs, name: "58"),
          Selected(status: 0.obs, name: "59"),
          Selected(status: 0.obs, name: "60"),
          Selected(status: 0.obs, name: "61"),
          Selected(status: 0.obs, name: "62"),
          Selected(status: 0.obs, name: "63"),
          Selected(status: 0.obs, name: "64"),
          Selected(status: 0.obs, name: "65"),
          Selected(status: 0.obs, name: "P1"),
          Selected(status: 0.obs, name: "P2"),
          Selected(status: 0.obs, name: "P3"),
          Selected(status: 0.obs, name: "P4"),
          Selected(status: 0.obs, name: "P5"),
          Selected(status: 0.obs, name: "P6"),
          Selected(status: 0.obs, name: "P7"),
          Selected(status: 0.obs, name: "P8"),
          Selected(status: 0.obs, name: "P9"),
          Selected(status: 0.obs, name: "P10s"),
          Selected(status: 0.obs, name: "S1"),
          Selected(status: 0.obs, name: "S2"),
          Selected(status: 0.obs, name: "S3"),
          Selected(status: 0.obs, name: "S4"),
          Selected(status: 0.obs, name: "S5"),
          Selected(status: 0.obs, name: "S6"),
          Selected(status: 0.obs, name: "S7"),
          Selected(status: 0.obs, name: "S8"),
          Selected(status: 0.obs, name: "S9"),
          Selected(status: 0.obs, name: "S10"),
          Selected(status: 0.obs, name: "S11"),
          Selected(status: 0.obs, name: "S12"),
          Selected(status: 0.obs, name: "S13"),
          Selected(status: 0.obs, name: "S14"),
          Selected(status: 0.obs, name: "S15"),
          Selected(status: 0.obs, name: "S16"),
          Selected(status: 0.obs, name: "S17"),
          Selected(status: 0.obs, name: "M18"),
          Selected(status: 0.obs, name: "M19"),
          Selected(status: 0.obs, name: "M20"),
          Selected(status: 0.obs, name: "M21"),
          Selected(status: 0.obs, name: "M22"),
          Selected(status: 0.obs, name: "SE1"),
          Selected(status: 0.obs, name: "SE2"),
          Selected(status: 0.obs, name: "SE3"),
          Selected(status: 0.obs, name: "SE4"),
          Selected(status: 0.obs, name: "SE5"),
          Selected(status: 0.obs, name: "SE6"),
          Selected(status: 0.obs, name: "SE7"),
          Selected(status: 0.obs, name: "SE8"),
        ]);
      }
      for (int i = 0; i < getDataListSanj.length; i++) {
        if (getDataListSanj[i].status.value == 0 &&
            getDataListSavar[i].status.value == 0) {
          list.add(getDataListSanj[i].name.toString());
        }
      }
    } else {
      if (!isNullEmptyOrFalse(box.read(DataDate.value + getSelectedText()))) {
        getDataList.value =
            ((jsonDecode(box.read(DataDate.value + getSelectedText()))
                        as List<dynamic>)
                    .toList())
                .map((e) => Selected.fromJson(e))
                .toList();

        if (!isNullEmptyOrFalse(getDataList)) {
          for (int i = 0; i < getDataList.length; i++) {
            if (getDataList[i].status.value == 0) {
              list.add(getDataList[i].name.toString());
            }
          }
        }
      } else {
        box.write(
            DataDate.value + getSelectedText(),
            jsonEncode(RxList<Selected>([
              Selected(status: 0.obs, name: "1"),
              Selected(status: 0.obs, name: "2"),
              Selected(status: 0.obs, name: "3"),
              Selected(status: 0.obs, name: "4"),
              Selected(status: 0.obs, name: "5"),
              Selected(status: 0.obs, name: "6"),
              Selected(status: 0.obs, name: "7"),
              Selected(status: 0.obs, name: "8"),
              Selected(status: 0.obs, name: "9"),
              Selected(status: 0.obs, name: "10"),
              Selected(status: 0.obs, name: "11"),
              Selected(status: 0.obs, name: "12"),
              Selected(status: 0.obs, name: "13"),
              Selected(status: 0.obs, name: "14"),
              Selected(status: 0.obs, name: "15"),
              Selected(status: 0.obs, name: "16"),
              Selected(status: 0.obs, name: "17"),
              Selected(status: 0.obs, name: "18"),
              Selected(status: 0.obs, name: "19"),
              Selected(status: 0.obs, name: "20"),
              Selected(status: 0.obs, name: "21"),
              Selected(status: 0.obs, name: "22"),
              Selected(status: 0.obs, name: "23"),
              Selected(status: 0.obs, name: "24"),
              Selected(status: 0.obs, name: "25"),
              Selected(status: 0.obs, name: "26"),
              Selected(status: 0.obs, name: "27"),
              Selected(status: 0.obs, name: "28"),
              Selected(status: 0.obs, name: "29"),
              Selected(status: 0.obs, name: "30"),
              Selected(status: 0.obs, name: "31"),
              Selected(status: 0.obs, name: "32"),
              Selected(status: 0.obs, name: "33"),
              Selected(status: 0.obs, name: "34"),
              Selected(status: 0.obs, name: "35"),
              Selected(status: 0.obs, name: "36"),
              Selected(status: 0.obs, name: "37"),
              Selected(status: 0.obs, name: "38"),
              Selected(status: 0.obs, name: "39"),
              Selected(status: 0.obs, name: "40"),
              Selected(status: 0.obs, name: "41"),
              Selected(status: 0.obs, name: "42"),
              Selected(status: 0.obs, name: "43"),
              Selected(status: 0.obs, name: "44"),
              Selected(status: 0.obs, name: "45"),
              Selected(status: 0.obs, name: "46"),
              Selected(status: 0.obs, name: "47"),
              Selected(status: 0.obs, name: "48"),
              Selected(status: 0.obs, name: "49"),
              Selected(status: 0.obs, name: "50"),
              Selected(status: 0.obs, name: "51"),
              Selected(status: 0.obs, name: "52"),
              Selected(status: 0.obs, name: "53"),
              Selected(status: 0.obs, name: "54"),
              Selected(status: 0.obs, name: "55"),
              Selected(status: 0.obs, name: "56"),
              Selected(status: 0.obs, name: "57"),
              Selected(status: 0.obs, name: "58"),
              Selected(status: 0.obs, name: "59"),
              Selected(status: 0.obs, name: "60"),
              Selected(status: 0.obs, name: "61"),
              Selected(status: 0.obs, name: "62"),
              Selected(status: 0.obs, name: "63"),
              Selected(status: 0.obs, name: "64"),
              Selected(status: 0.obs, name: "65"),
              Selected(status: 0.obs, name: "P1"),
              Selected(status: 0.obs, name: "P2"),
              Selected(status: 0.obs, name: "P3"),
              Selected(status: 0.obs, name: "P4"),
              Selected(status: 0.obs, name: "P5"),
              Selected(status: 0.obs, name: "P6"),
              Selected(status: 0.obs, name: "P7"),
              Selected(status: 0.obs, name: "P8"),
              Selected(status: 0.obs, name: "P9"),
              Selected(status: 0.obs, name: "P10s"),
              Selected(status: 0.obs, name: "S1"),
              Selected(status: 0.obs, name: "S2"),
              Selected(status: 0.obs, name: "S3"),
              Selected(status: 0.obs, name: "S4"),
              Selected(status: 0.obs, name: "S5"),
              Selected(status: 0.obs, name: "S6"),
              Selected(status: 0.obs, name: "S7"),
              Selected(status: 0.obs, name: "S8"),
              Selected(status: 0.obs, name: "S9"),
              Selected(status: 0.obs, name: "S10"),
              Selected(status: 0.obs, name: "S11"),
              Selected(status: 0.obs, name: "S12"),
              Selected(status: 0.obs, name: "S13"),
              Selected(status: 0.obs, name: "S14"),
              Selected(status: 0.obs, name: "S15"),
              Selected(status: 0.obs, name: "S16"),
              Selected(status: 0.obs, name: "S17"),
              Selected(status: 0.obs, name: "M18"),
              Selected(status: 0.obs, name: "M19"),
              Selected(status: 0.obs, name: "M20"),
              Selected(status: 0.obs, name: "M21"),
              Selected(status: 0.obs, name: "M22"),
              Selected(status: 0.obs, name: "SE1"),
              Selected(status: 0.obs, name: "SE2"),
              Selected(status: 0.obs, name: "SE3"),
              Selected(status: 0.obs, name: "SE4"),
              Selected(status: 0.obs, name: "SE5"),
              Selected(status: 0.obs, name: "SE6"),
              Selected(status: 0.obs, name: "SE7"),
              Selected(status: 0.obs, name: "SE8"),
            ]).map((e) => e.toJson()).toList()));
        list.clear();

        list.addAll([
          Selected(status: 0.obs, name: "1"),
          Selected(status: 0.obs, name: "2"),
          Selected(status: 0.obs, name: "3"),
          Selected(status: 0.obs, name: "4"),
          Selected(status: 0.obs, name: "5"),
          Selected(status: 0.obs, name: "6"),
          Selected(status: 0.obs, name: "7"),
          Selected(status: 0.obs, name: "8"),
          Selected(status: 0.obs, name: "9"),
          Selected(status: 0.obs, name: "10"),
          Selected(status: 0.obs, name: "11"),
          Selected(status: 0.obs, name: "12"),
          Selected(status: 0.obs, name: "13"),
          Selected(status: 0.obs, name: "14"),
          Selected(status: 0.obs, name: "15"),
          Selected(status: 0.obs, name: "16"),
          Selected(status: 0.obs, name: "17"),
          Selected(status: 0.obs, name: "18"),
          Selected(status: 0.obs, name: "19"),
          Selected(status: 0.obs, name: "20"),
          Selected(status: 0.obs, name: "21"),
          Selected(status: 0.obs, name: "22"),
          Selected(status: 0.obs, name: "23"),
          Selected(status: 0.obs, name: "24"),
          Selected(status: 0.obs, name: "25"),
          Selected(status: 0.obs, name: "26"),
          Selected(status: 0.obs, name: "27"),
          Selected(status: 0.obs, name: "28"),
          Selected(status: 0.obs, name: "29"),
          Selected(status: 0.obs, name: "30"),
          Selected(status: 0.obs, name: "31"),
          Selected(status: 0.obs, name: "32"),
          Selected(status: 0.obs, name: "33"),
          Selected(status: 0.obs, name: "34"),
          Selected(status: 0.obs, name: "35"),
          Selected(status: 0.obs, name: "36"),
          Selected(status: 0.obs, name: "37"),
          Selected(status: 0.obs, name: "38"),
          Selected(status: 0.obs, name: "39"),
          Selected(status: 0.obs, name: "40"),
          Selected(status: 0.obs, name: "41"),
          Selected(status: 0.obs, name: "42"),
          Selected(status: 0.obs, name: "43"),
          Selected(status: 0.obs, name: "44"),
          Selected(status: 0.obs, name: "45"),
          Selected(status: 0.obs, name: "46"),
          Selected(status: 0.obs, name: "47"),
          Selected(status: 0.obs, name: "48"),
          Selected(status: 0.obs, name: "49"),
          Selected(status: 0.obs, name: "50"),
          Selected(status: 0.obs, name: "51"),
          Selected(status: 0.obs, name: "52"),
          Selected(status: 0.obs, name: "53"),
          Selected(status: 0.obs, name: "54"),
          Selected(status: 0.obs, name: "55"),
          Selected(status: 0.obs, name: "56"),
          Selected(status: 0.obs, name: "57"),
          Selected(status: 0.obs, name: "58"),
          Selected(status: 0.obs, name: "59"),
          Selected(status: 0.obs, name: "60"),
          Selected(status: 0.obs, name: "61"),
          Selected(status: 0.obs, name: "62"),
          Selected(status: 0.obs, name: "63"),
          Selected(status: 0.obs, name: "64"),
          Selected(status: 0.obs, name: "65"),
          Selected(status: 0.obs, name: "P1"),
          Selected(status: 0.obs, name: "P2"),
          Selected(status: 0.obs, name: "P3"),
          Selected(status: 0.obs, name: "P4"),
          Selected(status: 0.obs, name: "P5"),
          Selected(status: 0.obs, name: "P6"),
          Selected(status: 0.obs, name: "P7"),
          Selected(status: 0.obs, name: "P8"),
          Selected(status: 0.obs, name: "P9"),
          Selected(status: 0.obs, name: "P10s"),
          Selected(status: 0.obs, name: "S1"),
          Selected(status: 0.obs, name: "S2"),
          Selected(status: 0.obs, name: "S3"),
          Selected(status: 0.obs, name: "S4"),
          Selected(status: 0.obs, name: "S5"),
          Selected(status: 0.obs, name: "S6"),
          Selected(status: 0.obs, name: "S7"),
          Selected(status: 0.obs, name: "S8"),
          Selected(status: 0.obs, name: "S9"),
          Selected(status: 0.obs, name: "S10"),
          Selected(status: 0.obs, name: "S11"),
          Selected(status: 0.obs, name: "S12"),
          Selected(status: 0.obs, name: "S13"),
          Selected(status: 0.obs, name: "S14"),
          Selected(status: 0.obs, name: "S15"),
          Selected(status: 0.obs, name: "S16"),
          Selected(status: 0.obs, name: "S17"),
          Selected(status: 0.obs, name: "M18"),
          Selected(status: 0.obs, name: "M19"),
          Selected(status: 0.obs, name: "M20"),
          Selected(status: 0.obs, name: "M21"),
          Selected(status: 0.obs, name: "M22"),
          Selected(status: 0.obs, name: "SE1"),
          Selected(status: 0.obs, name: "SE2"),
          Selected(status: 0.obs, name: "SE3"),
          Selected(status: 0.obs, name: "SE4"),
          Selected(status: 0.obs, name: "SE5"),
          Selected(status: 0.obs, name: "SE6"),
          Selected(status: 0.obs, name: "SE7"),
          Selected(status: 0.obs, name: "SE8"),
        ].map((e) => e.name).toList());
      }
    }

    dropdownValue.value = list.first.toString();
    hasData.value = true;
  }

  datePick({required BuildContext context}) async {
    DateTime? pickedDate = await showDatePicker(
        context: context,
        initialDate: DateTime.now(),
        firstDate: DateTime(1950),
        lastDate: DateTime(2100));
    if (pickedDate != null) {
      print(pickedDate);
      selectedDate.value = DateFormat('dd/MM/yyyy').format(pickedDate);
      DataDate.value = DateFormat('dd/MM/yyyy').format(pickedDate);
      data();
    } else {}
  }

  getSelectedText() {
    if (isFullDaySelected.isTrue) {
      return timeConstant.full;
    } else if (isSavarSelected.isTrue) {
      return timeConstant.savar;
    } else if (isSanjSelected.isTrue) {
      return timeConstant.Sanj;
    }
    return timeConstant.savar;
  }

  @override
  void onReady() {
    super.onReady();
  }

  @override
  void onClose() {
    super.onClose();
  }
}
